// <auto-generated />
using System;
using BattleHub.Trivia.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleHub.Trivia.Data.Migrations
{
    [DbContext(typeof(TriviaDbContext))]
    [Migration("20260930163936_CrearResultadosYPreguntas")]
    partial class CrearResultadosYPreguntas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.AnswerOptionRecord", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AnswerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("QuestionId", "AnswerId");

                    b.ToTable("AnswerOptions", (string)null);
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.MatchResultRecord", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("DecidedByTiebreak")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsTie")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metadata");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WinnerUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("MatchId");

                    b.ToTable("MatchResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchResults_Metadata_IsJson", "ISJSON([Metadata]) = 1");
                        });
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.PlayerResultRecord", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<long>("CorrectAnswersTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("MatchId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerResults", (string)null);
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.QuestionRecord", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorrectAnswerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("QuestionId");

                    b.HasIndex("Category");

                    b.HasIndex("Difficulty");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.AnswerOptionRecord", b =>
                {
                    b.HasOne("BattleHub.Trivia.Data.Persistence.QuestionRecord", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.PlayerResultRecord", b =>
                {
                    b.HasOne("BattleHub.Trivia.Data.Persistence.MatchResultRecord", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.MatchResultRecord", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("BattleHub.Trivia.Data.Persistence.QuestionRecord", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
